theme = "lynx"
title = "Lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Lynx"
  image = "author.jpg"
  links = [
    { link = { href = "readme/", text = "View the readme" } },
    { github = "https://github.com/jpanther/lynx" },
    { twitter = "https://twitter.com/jpanther" },
    { font-awesome = { href = "https://fontawesome.com/", text = "FontAwesome" } },
  ]

[markup.highlight]
  noClasses = false
